fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
cms_frontend:
    resource: "@CmsFrontendBundle/Resources/config/routing.yml"
    prefix:   /admin

cms_admin:
    resource: "@CmsAdminBundle/Resources/config/routing.yml"
    prefix:   /

