parameters:
#    bootcamp_admin.example.class: Cms\AdminBundle\Example

services:
#    cms_admin.example:
#       class: %Cms\AdminBundle\Example
#       arguments: [@service_id, "plain_value", %parameter%]
